<a href="https://colab.research.google.com/github/Thunder-Duckling/Basic-ML-Projects-/blob/main/Linear_Regression_Apples%26Oranges_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import math

In [ ]:
#Training data now

In [ ]:
# Input temp, rainfall and humidity
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [ ]:
# Targets ---> Apples and Oranges
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.4212, -0.8569, -0.5304],
        [-0.2171,  1.9056, -0.4092]], requires_grad=True)
tensor([0.4057, 0.3411], requires_grad=True)


In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
inputs @ w.t() + b # Transposition matrix

tensor([[-110.5654,   94.5750],
        [-147.2814,  122.0927],
        [-181.8336,  213.0751],
        [ -99.0320,   44.9989],
        [-148.0524,  139.6590]], grad_fn=<AddBackward0>)

In [ ]:
# Training the model with gradient descent
'''
1. Generate Predictions
2. Calculate Loss
3. compute gradients with respect to weights and biases
4. Adjust the weight by subtracting small quantity proportional to the gradient
5. Reset the gradient to zero

'''

'\n1. Generate Predictions\n2. Calculate Loss\n3. compute gradients with respect to weights and biases\n4. Adjust the weight by subtracting small quantity proportional to the gradient\n5. Reset the gradient to zero\n\n'

In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
# Generating predictions now
preds = model(inputs)
print(preds)

tensor([[-110.5654,   94.5750],
        [-147.2814,  122.0927],
        [-181.8336,  213.0751],
        [ -99.0320,   44.9989],
        [-148.0524,  139.6590]], grad_fn=<AddBackward0>)


In [ ]:
# How well our model is performing: can be checked by 3 steps:
# 1. Subtrcact the predictions and actual values and store in a variable
# 2. square the variable to remove negative values
# 3. calculate the average of the resulting elements in the matrix

In [ ]:
'''
diff = preds - targets
torch.sum(diff * diff) / diff.numel()
# the result is called as MSE --> Mean Square Error
'''
#MSE Loss
def mse(t1,t2):
  diff = t1 - t2
  return torch.sum(diff*diff) / diff.numel()

In [ ]:
# Computing loss
loss = mse(preds,targets)
print(loss)

tensor(25598.4961, grad_fn=<DivBackward0>)


In [ ]:
# Computing Gradients
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[-0.4212, -0.8569, -0.5304],
        [-0.2171,  1.9056, -0.4092]], requires_grad=True)
tensor([[-17754.6562, -20173.1504, -12254.5049],
        [  2584.2627,   3311.9946,   1758.6218]])


In [ ]:
print(b)
print(b.grad)

tensor([0.4057, 0.3411], requires_grad=True)
tensor([-213.5529,   30.8802])


In [ ]:
with torch.no_grad(): #torch.no_grad --> tells pytorch not to track, calculate or modify the gradieant while updating weights and biases
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
print(w)
print(b)

tensor([[-0.2437, -0.6552, -0.4078],
        [-0.2429,  1.8725, -0.4268]], requires_grad=True)
tensor([0.4078, 0.3407], requires_grad=True)


In [ ]:
# lets see if loss is decreased now
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(17466.2207, grad_fn=<DivBackward0>)


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# Train it multiple times to reduce the loss even further, we repeat the process  of adjusting weights and biases using the gradients multiple times.
# Each iteration is called an "epoche"
# Training the model for 100 times now

In [ ]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Veryfying if loss is lower now
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(262.8852, grad_fn=<DivBackward0>)


In [ ]:
preds

tensor([[ 62.5490,  69.2440],
        [ 82.9536,  88.8258],
        [108.3407, 161.6095],
        [ 51.6787,  29.3728],
        [ 85.4459, 103.0596]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# gives us the standard deviation to the prediction and actual values
math.sqrt(loss)

16.213735639533287